version: '3'
services:
  app:
    container_name: docker-angular-app
    restart: always
    build: .
    ports:
      - '80:4200'
    volumes:
      - '/usr/src/app/node_modules'
      - '.:/usr/src/app'
